### ISSUE TITLE
como instala o modulo

### ISSUE THREAD

**Issue by marcelowu** [cassiopaixao/Grand.Plugin.Shipping.Rodonaves#1]
como instala o modulo no ubuntu?

**Comment by cassiopaixao** [comment]
Estou desenvolvendo no VisualStudio 2019. Não cheguei ainda a testar ou instalar o plugin no grandnode em outro ambiente. Mas... segue algumas informações que podem ajudar nesse setup.

No arquivo [.csproj](https://github.com/cassiopaixao/Grand.Plugin.Shipping.Rodonaves/blob/master/Grand.Plugin.Shipping.Rodonaves.csproj) há as indicações para compilação no Visual Studio. Segue as principais, que podem ajudar a portar a outro ambiente):

* Considerando que o projeto está na pasta `\Plugins\Grand.Plugin.Shipping.Rodonaves\` , o _output_ da compilação será no diretório `\Grand.Web\Plugins\Shipping.Rodonaves` .
    * Nota: É nesse o diretório `\Grand.Web\Plugins` que o Grandnode busca possíveis plugins para instalação.
* Alguns arquivos estáticos são simplesmente copiados:
    * `Description.txt`
    * `logo.jpg`
    * `Views\_ViewImports.cshtml`
    * `Views\Configure.cshtml`

**Comment by marcelowu** [comment]
eu fiz isso , mas nao aparece nada no admin

**Comment by marcelowu** [comment]
How to upgrade plugin to 4.80
https://grandnode.com/how-to-upgrade-plugin-to-4800
